/**
 * Seed product catalog — this is the STARTING data only. Once the
 * site runs, the live copy lives in localStorage (see store.js) so
 * stock counts can change as you sell things, without editing this
 * file. Use the "Reset demo data" button in admin.html to start over
 * from this list.
 *
 * `stock` is a starting inventory count — adjust these (or use the
 * admin panel) to match what's actually on the shelf.
 *
 * Prices are placeholders based on the existing catalog's range —
 * adjust freely in admin.html or here before this goes live.
 */
export const PRODUCTS = [
  {
    id: "worldwide-jersey",
    name: "Worldwide No.10 Jersey",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    stock: 12,
    allowDirectCheckout: true,
    image: "assets/shop/worldwide-jersey.jpg",
    alt: "Black PeaceMagents Worldwide No.10 football-style jersey, front and back",
    description:
      "Football-cut jersey in black and bone, hand-tagged with the PeaceMagents crest and a raglan No.10 back print.",
  },
  {
    id: "sage-graphic-tee",
    name: "Sage Wash Graphic Tee",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: null,
    stock: 8,
    allowDirectCheckout: true,
    image: "assets/shop/sage-graphic-tee.jpg",
    alt: "Sage green washed t-shirt with a brown and red PEACE MAGENTS hand-drawn print",
    description:
      "Garment-washed heavyweight cotton with a hand-drawn back graphic and a quiet chest line: creativity reflects the nature of god.",
  },
  {
    id: "camo-snapback",
    name: "PM Camo Snapback",
    price: 5,
    currency: "USD",
    category: "caps",
    sizes: ["One size"],
    tag: null,
    stock: 15,
    allowDirectCheckout: true,
    image: "assets/shop/camo-snapback.jpg",
    alt: "Camouflage snapback cap embroidered with the PeaceMagents wordmark and wing logo",
    description:
      "Structured camo snapback with an embroidered wordmark and the PM wing pin on the side panel.",
  },
  {
    id: "orbit-logo-tee",
    name: "Orbit Logo Tee — Black",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: null,
    stock: 2,
    allowDirectCheckout: true,
    image: "assets/shop/orbit-logo-tee.jpg",
    alt: "Black t-shirt with a small chest logo and large back print of the Pm orbit mark",
    description:
      "Clean black tee, small chest hit up front, full-back Pm orbit mark for anyone who lets the logo do the talking.",
  },
  {
    id: "orbit-logo-tee-bone",
    name: "Orbit Logo Tee — Bone",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    stock: 6,
    allowDirectCheckout: true,
    image: "assets/shop/orbit-logo-tee-bone.jpg",
    alt: "Bone/cream t-shirt with a small chest logo and large back print of the Pm orbit mark",
    description:
      "Same Pm orbit mark front and back, in a warmer bone colorway for anyone who wants the logo tee without going full black.",
  },
  {
    id: "chrome-claw-tee",
    name: "Chrome Claw Tee",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: "Limited",
    stock: 4,
    allowDirectCheckout: false,
    image: "assets/shop/chrome-claw-tee.jpg",
    alt: "Black t-shirt with a chrome PM logo and red clawed hand graphic on the lower back",
    description:
      "Oversized black tee with a chrome PM mark reaching up from a red-clawed hand print, placed low on the back. Limited run — enquire to confirm sizing before it's gone.",
  },
  {
    id: "camo-raglan",
    name: "Camo Sleeve Raglan",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: null,
    stock: 0,
    allowDirectCheckout: true,
    image: "assets/shop/camo-raglan.jpg",
    alt: "White long-sleeve raglan with camouflage sleeves and a graffiti-style Magents logo",
    description:
      "White-body raglan with camo sleeves and a graffiti-tag logo up front — a target mark watching the whole thing.",
  },
  {
    id: "street-alert-tee-black",
    name: "Street Alert Tee — Black",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    stock: 6,
    allowDirectCheckout: true,
    image: "assets/shop/street-alert-tee-black.jpg",
    alt: "Black t-shirt with a green PEACE MAGENTS back print of a character reaching toward a glowing rock with an exclamation mark",
    description:
      "Black heavyweight tee, full-back comic-style print — a PeaceMagents character caught mid-reach next to a lit-up exclamation mark.",
  },
  {
    id: "resilient-manifesto-tee-bone",
    name: "Resilient Manifesto Tee — Bone",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    stock: 8,
    allowDirectCheckout: true,
    image: "assets/shop/resilient-manifesto-tee-bone.jpg",
    alt: "Bone colored t-shirt with green PEACEMAGENT wordmark and a short manifesto printed below it",
    description:
      "Stay resilient even through the dark times. Break through whatever comes in your path. We're stronger when we rise above it — printed in full on the chest.",
  },
  {
    id: "resilient-manifesto-tee-charcoal",
    name: "Resilient Manifesto Tee — Charcoal Wash",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    stock: 5,
    allowDirectCheckout: true,
    image: "assets/shop/resilient-manifesto-tee-charcoal.jpg",
    alt: "Charcoal acid-wash t-shirt with green PeaceMagents wordmark and a short manifesto printed below it",
    description:
      "Same manifesto print as the Bone colorway, on a marbled charcoal wash for a heavier, worn-in look.",
  },
  {
    id: "wanted-mugshot-tee",
    name: "Wanted Mugshot Tee",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    stock: 9,
    allowDirectCheckout: true,
    image: "assets/shop/wanted-mugshot-tee.jpg",
    alt: "White t-shirt with a small kanji and Magents chest logo, and a large Wanted By Police mugshot-style back print",
    description:
      "Small 和平 Magents chest hit, full mugshot-poster back print — \"Wanted by Police\" height chart and all.",
  },
  {
    id: "go-crazy-tee",
    name: "Go Crazy Tee",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: null,
    stock: 7,
    allowDirectCheckout: true,
    image: "assets/shop/go-crazy-tee.jpg",
    alt: "Black t-shirt with a purple smoke Go Crazy graphic and a character leaning on a car",
    description:
      "Black tee, purple smoke lettering, a character posted up against the car — for the ones who go crazy quietly.",
  },
  {
    id: "worldwide-mascot-tee",
    name: "Worldwide Mascot Tee",
    price: 15,
    currency: "USD",
    category: "tees",
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    stock: 10,
    allowDirectCheckout: true,
    image: "assets/shop/worldwide-mascot-tee.jpg",
    alt: "White t-shirt with a small kanji and Magents chest logo, and a large back print of a mascot dabbing on top of the globe",
    description:
      "Small 和平 Magents chest hit, big back print of the PeaceMagents mascot dabbing on top of the world — one mindset, no borders, worn on your back.",
  },
  {
    id: "wing-logo-fuzzy-cap",
    name: "Wing Logo Fuzzy Cap",
    price: 5,
    currency: "USD",
    category: "caps",
    sizes: ["One size"],
    tag: "New",
    stock: 10,
    allowDirectCheckout: true,
    image: "assets/shop/wing-logo-fuzzy-cap.jpg",
    alt: "Black fuzzy cap with a wing graphic and embroidered 和平 Magents logo",
    description:
      "Fuzzy black cap with a winged side patch and embroidered 和平 Magents script across the front.",
  },
];
